name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "[BUG] <write a small description here>"
labels: ["bug", "goal: fix", "priority: medium"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional information?
      description: Any additional information or Is there anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues)."
          required: true
        - label: "I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: "The changes don't break the code"
          required: true
        - label: "Please attach the screenshots and video of the development work once it is done "
          required: true

        
