name: Other
description: Use this for any other question or issue. Please do not create blank issues
title: "[OTHER]"
labels: ["status: awaiting triage"]
body:
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share or ask?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/Collect-your-GamingTools/issues)."
          required: true

        - label: "I have read the [Code Of Conduct](https://github.com/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)"
          required: true

        - label: "The changes don't break the code"
          required: true
        - label: "Please attach the screenshots and video of the development work once it is done "
          required: true
